config/routes.rb
Visually::Application.routes.draw do
  authenticated :user do
    root :to => 'dashboard#index'
  end
  root :to => "home#index"
  
  devise_for :users, controllers: { registrations: 'devise_users/registrations', :sessions => "devise_users/sessions",
                                    :passwords => "devise_users/passwords", :confirmations => "devise_users/confirmations"}
  devise_scope :user do
    get 'users/email_available', to: 'devise_users/registrations#email_available'
    get 'users/current', to: 'devise_users/sessions#current'
    namespace :devise_users do
      resources :sessions, :only => [:create, :destroy]
    end
  end
  resources :users, only: [:index, :show, :destroy, :update]

  post 'collections/:id/load_csv' => 'collections#load_csv'

  get "api/v1/charts/dynamic" => 'api/v1/charts#dynamic'
  get "api/v1/charts/exists" => 'api/v1/charts#exists'
  #post "api/v1/charts" => 'api/v1/charts#create'

  namespace :api do
    namespace :v1 do
      resources 'charts', controller: 'charts'
      resources 'collections' do
        resources 'data', controller: 'data'
      end
    end
  end

  resources :accounts
  resources :uploads
  resources :collections

  put 'accounts/:id/cc' => 'accounts#updateCC'

  get "dashboard" => "dashboard#index"
  get "bonuses" => "bonuses#index"
  post "bonuses" => "bonuses#create"
  get "charts/:chart_id" => 'api/v1/charts#show'

  get "feedback" => "feedback#index"


  mount StripeEvent::Engine => '/stripe'

  #get '/*a' => redirect('/')
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%=name == :notice ? "success" : "error"%>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><a href="/" class="brand"><i class="icon-bar-chart"></i> Slik.IO</a></li>
</ul>
<ul class="nav">
  <% unless user_signed_in? %>
    <li>
      <a href="#/users/sign_in">Sign in</a>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
        <%= link_to 'Admin', rails_admin_path %>
      </li>
    <% end %>
  <% else %>
    <li>
      <a href="#/users/sign_up">Sign Up</a>
    </li>
  <% end %>
</ul>
<% if user_signed_in? %>
  <ul class="nav pull-right user_tool">
    <li class="trial_title">
      Trial period ends in <%=distance_of_time_in_words(Time.now, current_user.trial_ends_at) %>
    </li>
    <li>
      <div class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" >
          <span class="icon-stack">
            <i class="icon-sign-blank icon-stack-base"></i>
            <i class="icon-user icon-light"></i>
          </span>
          <%= current_user.first_name+" "+current_user.last_name %>
        </a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <li><a href="#/my_account">Manage account</a></li>
          <li class="divider"></li>
           <li><%= link_to 'Get Bonuses', '#/bonuses' %></li>
           <li><%= link_to 'Give Us Feedback', "#/feedback" %></li>
          <li class="divider"></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete'%></li>
        </ul>
      </div>
    </li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.haml
= link_to "Slik.IO", root_path, :class => 'brand'
%ul.nav
  - unless user_signed_in?
    %li
      / = link_to 'Log in', new_user_session_path, :method=>'delete'
      %a{href: "#/users/sign_in"} Sign in
  - if user_signed_in?
    %li
      %a{href: '#/my_account'} Account
      / = link_to 'Edit account', edit_user_registration_path
    %li 
      = link_to 'Dashboard', "#/dashboard"
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      %a{href: "#/users/sign_up"} Sign Up
      / = link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  %ul.nav.pull-right
    - if current_user.rewards.has_left
      %li.pull-right
        = link_to 'Bonuses', '#/bonuses'
    %li.topbar-text.pull-right
      = "Trial period ends in " + distance_of_time_in_words(Time.now, current_user.trial_ends_at)

    %li.pull-right
      / %i.icon-off
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
     

app/views/layouts/_subnavigation.html.erb
<ul class="nav inline pull-right">
  <li><a class="btn btn-danger" href="#/charts/new"><i class="icon-plus"></i> Create chart</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="visApp">
  <head>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title><%=content_for?(:title) ? yield(:title) : "Slik.IO" %></title>
    <meta content="<%=content_for?(:description) ? yield(:description) : "Slik.IO"%>" name="description">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>

    <header id="top_header" ng-cloak ng-if="userLoggedIn">
      <div class="navbar">
        <div class="" ng-include="'/html/layout/navigation.html'">
        </div>
      </div>
    </header>

    <div class="wrapper">
      <div id="main" role="main">
        <div class="row-fluid">
          <div ng-include="'/html/layout/_flash.html'"></div>
          <div class="section0" ui-view>
          </div>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      if (window.history && window.location.pathname != '/'){
        window.history.replaceState({}, null, '/');
      }

      var $$initialTransition = {
        transitionTo: '<%= @transition_to if @transition_to %>'
        <%= raw ", transitionParams: #{@transition_params.to_json()}" if @transition_params %>
      };
    </script>

    <script type="text/javascript">
      slikIObaseUrl = "<%=request.protocol%><%=request.host_with_port%>";
    </script>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "api/charts" %>

    <!-- Segment.IO -->
    <script type="text/javascript">
      var analytics=analytics||[];(function(){var e=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group"],t=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var n=0;n<e.length;n++)analytics[e[n]]=t(e[n])})(),analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n)};
      analytics.load("<%=ENV['SEGMENTIO_CLIENT_KEY']%>");
    </script>
    <% if user_signed_in? %>
      <script type="text/javascript">
        analytics.identify('<%=current_user.email%>', {
          name             : '<%=current_user.first_name%> <%=current_user.last_name%>',
          first_name       : '<%=current_user.first_name%>',
          last_name        : '<%=current_user.last_name%>',
          email            : '<%=current_user.email%>'
        });
      </script>
    <% end %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript">
      Stripe.setPublishableKey('<%= ENV['STRIPE_PUBLIC_KEY'] %>')
    </script>

    <!-- begin olark code -->
    <script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
    f[z]=function(){
    (a.s=a.s||[]).push(arguments)};var a=f[z]._={
    },q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
    f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
    0:+new Date};a.P=function(u){
    a.p[u]=new Date-a.p[0]};function s(){
    a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
    hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
    return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
    b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
    b.contentWindow[g].open()}catch(w){
    c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
    var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
    b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
    loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
    /* custom configuration goes here (www.olark.com/documentation) */
    olark.identify('3033-179-10-8194');/*]]>*/</script><noscript><a href="https://www.olark.com/site/3033-179-10-8194/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
    <!-- end olark code -->

  </body>
</html>